---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  sources:
  - chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 6.6.0
    helm:
      valueFiles:
        - $values/values/kind/argo-cd/values.yaml
  - ref: values
    repoURL: 'git@github.com:CloudNative-Solutions/argocd-gitops.git'
    targetRevision: HEAD