---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iam-resources
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: IAM
    repoURL: git@github.com:CloudNative-Solutions/argocd-gitops.git
    targetRevision: HEAD
    directory:
      recurse: true
  syncPolicy:
    automated: {}