apiVersion: iam.services.k8s.aws/v1alpha1
kind: Policy
metadata:
  name: ACKIAMController
spec:
  name: ACKIAMControllerPolicy
  policyDocument: |-
    {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Sid": "VisualEditor0",
                "Effect": "Allow",
                "Action": [
                    "iam:GetGroup",
                    "iam:CreateGroup",
                    "iam:DeleteGroup",
                    "iam:UpdateGroup",
                    "iam:GetRole",
                    "iam:CreateRole",
                    "iam:DeleteRole",
                    "iam:UpdateRole",
                    "iam:PutRolePermissionsBoundary",
                    "iam:PutUserPermissionsBoundary",
                    "iam:GetUser",
                    "iam:CreateUser",
                    "iam:DeleteUser",
                    "iam:UpdateUser",
                    "iam:GetPolicy",
                    "iam:CreatePolicy",
                    "iam:DeletePolicy",
                    "iam:GetPolicyVersion",
                    "iam:CreatePolicyVersion",
                    "iam:DeletePolicyVersion",
                    "iam:ListPolicyVersions",
                    "iam:ListPolicyTags",
                    "iam:ListAttachedGroupPolicies",
                    "iam:GetGroupPolicy",
                    "iam:PutGroupPolicy",
                    "iam:AttachGroupPolicy",
                    "iam:DetachGroupPolicy",
                    "iam:DeleteGroupPolicy",
                    "iam:ListAttachedRolePolicies",
                    "iam:ListRolePolicies",
                    "iam:GetRolePolicy",
                    "iam:PutRolePolicy",
                    "iam:AttachRolePolicy",
                    "iam:DetachRolePolicy",
                    "iam:DeleteRolePolicy",
                    "iam:ListAttachedUserPolicies",
                    "iam:ListUserPolicies",
                    "iam:GetUserPolicy",
                    "iam:PutUserPolicy",
                    "iam:AttachUserPolicy",
                    "iam:DetachUserPolicy",
                    "iam:DeleteUserPolicy",
                    "iam:ListRoleTags",
                    "iam:ListUserTags",
                    "iam:TagPolicy",
                    "iam:UntagPolicy",
                    "iam:TagRole",
                    "iam:UntagRole",
                    "iam:TagUser",
                    "iam:UntagUser",
                    "iam:RemoveClientIDFromOpenIDConnectProvider",
                    "iam:ListOpenIDConnectProviderTags",
                    "iam:UpdateOpenIDConnectProviderThumbprint",
                    "iam:UntagOpenIDConnectProvider",
                    "iam:AddClientIDToOpenIDConnectProvider",
                    "iam:DeleteOpenIDConnectProvider",
                    "iam:GetOpenIDConnectProvider",
                    "iam:TagOpenIDConnectProvider",
                    "iam:CreateOpenIDConnectProvider",
                    "iam:UpdateAssumeRolePolicy"
                ],
                "Resource": "*"
            }
        ]
    }
---
apiVersion: iam.services.k8s.aws/v1alpha1
kind: Role
metadata:
  name: ack-iam-role
spec:
  name: ack-iam-role
  assumeRolePolicyDocument: >
    {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Effect": "Allow",
                "Principal": {
                    "Service": "ec2.amazonaws.com"
                },
                "Action": "sts:AssumeRole"
            }
        ]
    }
  policyRefs:
    - from:
        name: ACKIAMController