apiVersion: iam.services.k8s.aws/v1alpha1
kind: Policy
metadata:
  name: AWSIAMManagedPolicyCloudProviderNodes
spec:
  name: nodes.cluster-api-provider-aws.sigs.k8s.io
  policyDocument: |-
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Effect": "Allow",
          "Action": [
            "ec2:DescribeInstances",
            "ec2:DescribeRegions",
            "ecr:GetAuthorizationToken",
            "ecr:BatchCheckLayerAvailability",
            "ecr:GetDownloadUrlForLayer",
            "ecr:GetRepositoryPolicy",
            "ecr:DescribeRepositories",
            "ecr:ListImages",
            "ecr:BatchGetImage"
          ],
          "Resource": [
            "*"
          ]
        }
      ]
    }