apiVersion: iam.services.k8s.aws/v1alpha1
kind: Policy
metadata:
  name: AWSIAMManagedPolicyControllersEKS
spec:
  name: controllers-eks.cluster-api-provider-aws.sigs.k8s.io
  policyDocument: |-
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Effect": "Allow",
          "Action": [
            "ssm:GetParameter"
          ],
          "Resource": [
            "arn:*:ssm:*:*:parameter/aws/service/eks/optimized-ami/*"
          ]
        },
        {
          "Effect": "Allow",
          "Action": [
            "iam:CreateServiceLinkedRole"
          ],
          "Resource": [
            "arn:*:iam::*:role/aws-service-role/eks.amazonaws.com/AWSServiceRoleForAmazonEKS"
          ],
          "Condition": {
            "StringLike": {
              "iam:AWSServiceName": "eks.amazonaws.com"
            }
          }
        },
        {
          "Effect": "Allow",
          "Action": [
            "iam:CreateServiceLinkedRole"
          ],
          "Resource": [
            "arn:*:iam::*:role/aws-service-role/eks-nodegroup.amazonaws.com/AWSServiceRoleForAmazonEKSNodegroup"
          ],
          "Condition": {
            "StringLike": {
              "iam:AWSServiceName": "eks-nodegroup.amazonaws.com"
            }
          }
        },
        {
          "Effect": "Allow",
          "Action": [
            "iam:CreateServiceLinkedRole"
          ],
          "Resource": [
            "arn:aws:iam::*:role/aws-service-role/eks-fargate-pods.amazonaws.com/AWSServiceRoleForAmazonEKSForFargate"
          ],
          "Condition": {
            "StringLike": {
              "iam:AWSServiceName": "eks-fargate.amazonaws.com"
            }
          }
        },
        {
          "Effect": "Allow",
          "Action": [
            "iam:GetRole",
            "iam:ListAttachedRolePolicies"
          ],
          "Resource": [
            "arn:*:iam::*:role/*"
          ]
        },
        {
          "Effect": "Allow",
          "Action": [
            "iam:GetPolicy"
          ],
          "Resource": [
            "arn:aws:iam::aws:policy/AmazonEKSClusterPolicy"
          ]
        },
        {
          "Effect": "Allow",
          "Action": [
            "eks:DescribeCluster",
            "eks:ListClusters",
            "eks:CreateCluster",
            "eks:TagResource",
            "eks:UpdateClusterVersion",
            "eks:DeleteCluster",
            "eks:UpdateClusterConfig",
            "eks:UntagResource",
            "eks:UpdateNodegroupVersion",
            "eks:DescribeNodegroup",
            "eks:DeleteNodegroup",
            "eks:UpdateNodegroupConfig",
            "eks:CreateNodegroup",
            "eks:AssociateEncryptionConfig",
            "eks:ListIdentityProviderConfigs",
            "eks:AssociateIdentityProviderConfig",
            "eks:DescribeIdentityProviderConfig",
            "eks:DisassociateIdentityProviderConfig"
          ],
          "Resource": [
            "arn:*:eks:*:*:cluster/*",
            "arn:*:eks:*:*:nodegroup/*/*/*"
          ]
        },
        {
          "Effect": "Allow",
          "Action": [
            "ec2:AssociateVpcCidrBlock",
            "ec2:DisassociateVpcCidrBlock",
            "eks:ListAddons",
            "eks:CreateAddon",
            "eks:DescribeAddonVersions",
            "eks:DescribeAddon",
            "eks:DeleteAddon",
            "eks:UpdateAddon",
            "eks:TagResource",
            "eks:DescribeFargateProfile",
            "eks:CreateFargateProfile",
            "eks:DeleteFargateProfile"
          ],
          "Resource": [
            "*"
          ]
        },
        {
          "Effect": "Allow",
          "Action": [
            "iam:PassRole"
          ],
          "Resource": [
            "*"
          ],
          "Condition": {
            "StringEquals": {
              "iam:PassedToService": "eks.amazonaws.com"
            }
          }
        },
        {
          "Effect": "Allow",
          "Action": [
            "kms:CreateGrant",
            "kms:DescribeKey"
          ],
          "Resource": [
            "*"
          ],
          "Condition": {
            "ForAnyValue:StringLike": {
              "kms:ResourceAliases": "alias/cluster-api-provider-aws-*"
            }
          }
        }
      ]
    }
