apiVersion: iam.services.k8s.aws/v1alpha1
kind: Role
metadata:
  name: controllers.cluster-api-provider-aws.sigs.k8s.io
spec:
  name: controllers.cluster-api-provider-aws.sigs.k8s.io
  assumeRolePolicyDocument: >
    {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Effect": "Allow",
                "Principal": {
                    "Service": "ec2.amazonaws.com"
                },
                "Action": "sts:AssumeRole"
            }
        ]
    }
  policyRefs:
    - from:
        name: AWSIAMManagedPolicyControllers
    - from:
        name: AWSIAMManagedPolicyControllersEKS
---
apiVersion: iam.services.k8s.aws/v1alpha1
kind: InstanceProfile
metadata:
  name: controllers.cluster-api-provider-aws.sigs.k8s.io
spec:
  name: controllers.cluster-api-provider-aws.sigs.k8s.io
  roleRefs:
    from:
      name: controllers.cluster-api-provider-aws.sigs.k8s.io