apiVersion: iam.services.k8s.aws/v1alpha1
kind: Role
metadata:
  name: eks-nodegroup.cluster-api-provider-aws.sigs.k8s.io
spec:
  name: eks-nodegroup.cluster-api-provider-aws.sigs.k8s.io
  assumeRolePolicyDocument: >
    {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Effect": "Allow",
                "Principal": {
                    "Service": [
                        "ec2.amazonaws.com",
                        "eks.amazonaws.com"
                    ]
                },
                "Action": "sts:AssumeRole"
            }
        ]
    }
  policies:
    - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
    - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
    - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy